name: "Push Metrics"
description: "Push a metric value to Prometheus Pushgateway"
inputs:
  value:
    description: "Metric value"
    required: true
  metric_name:
    description: "Metric name"
    required: true
  job:
    description: "Job name"
    required: false
    default: "ci-default"
  pushgateway_url:
    description: "Pushgateway URL"
    required: false
    default: "http://host.docker.internal:9091"

runs:
  using: "composite"
  steps:
    - name: Push metrics
      shell: bash
      run: |
        set -euo pipefail

        value="${{ inputs.value }}"
        metric_name="${{ inputs.metric_name }}"
        job="${{ inputs.job }}"
        uri="${{ inputs.pushgateway_url }}"

        echo "${metric_name} ${value}" | curl -v -H "Content-Type: text/plain" --data-binary @- "$uri/metrics/job/${job}"
      env:
        VALUE: "${{ inputs.value }}"
        METRIC_NAME: "${{ inputs.metric_name }}"
        JOB: "${{ inputs.job }}"
        PUSHGATEWAY_URL: "${{ inputs.pushgateway_url }}"
