name: "Push Metrics"
description: "Push a metric value to Prometheus Pushgateway"
inputs:
  value:
    description: "Metric value"
    required: true
  metric_name:
    description: "Metric name"
    required: true
  job:
    description: "Job name"
    required: false
    default: "ci-default"
  pushgateway_url:
    description: "Pushgateway URL"
    required: false
    default: "http://pushgateway:9091"
runs:
  using: "composite"
  steps:
    - name: Push metric
      run: "${{ github.action_path }}/push.sh"
      shell: bash
      env:
        VALUE: "${{ inputs.value }}"
        METRIC_NAME: "${{ inputs.metric_name }}"
        JOB: "${{ inputs.job }}"
        PUSHGATEWAY_URL: "${{ inputs.pushgateway_url }}"
