name: Buildx Remote Build & Push
description: Build and push a Docker image using Buildx with a remote Git context
inputs:
  repository:
    description: Git repository URL for the build context (e.g. git://github.com/org/repo.git#main)
    required: true
  file:
    description: Path to Dockerfile within the remote repository
    required: true
  tag:
    description: Full image tag including registry
    required: true
  registry-token:
    description: Token used to login to ghcr.io
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      shell: bash
      run: |
        REGISTRY_USER="${{ github.triggering_actor || github.actor }}"
        echo "${{ inputs.registry-token }}" | docker login ghcr.io -u "$REGISTRY_USER" --password-stdin

    - name: Build & Push image from remote repo
      shell: bash
      run: |
        docker buildx build \
          --build-context repo=${{ inputs.repository }} \
          --file ${{ inputs.file }} \
          --tag ${{ inputs.tag }} \
          --push .
