---
name: Build and Deploy
inputs:
  project:
    description: "Project folder under ./projects containing values.yaml"
    required: false
    default: ''
  suffix:
    description: "Optional suffix appended to the ephemeral folder name"
    required: false
    default: ''
  app-dir:
    description: "Path to application Dockerfile"
    required: false
    default: ./app
  registry-token:
    description: "Token used to login to ghcr.io"
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Checkout to ephemeral workspace
      uses: johnhojohn969/setup-ephemeral-action/.github/actions/checkout@main
      with:
        suffix: ${{ inputs.suffix }}
    - name: Log in to GitHub Container Registry
      shell: bash
      run: |
        REGISTRY_USER="${{ github.triggering_actor || github.actor }}"
        echo "${{ inputs.registry-token }}" | \
          docker login ghcr.io -u "$REGISTRY_USER" --password-stdin
    - name: Extract repo name for image prefix
      id: repo
      shell: bash
      run: |
        repo_name=$(basename "${{ github.repository }}")
        echo "name=${repo_name,,}" >> "$GITHUB_OUTPUT"
    - name: Build & Push Image
      working-directory: ${{ env.WORK_DIR }}
      shell: bash
      run: |
        if [ ! -d "${{ inputs.app-dir }}" ]; then
        echo "App directory '${{ inputs.app-dir }}' does not exist" \
          >&2
          exit 1
        fi
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}:latest"
        docker build -t "$IMAGE" "${{ inputs.app-dir }}"
        docker push "$IMAGE"
    - name: Determine project name
      working-directory: ${{ env.WORK_DIR }}
      id: vars
      shell: bash
      run: |
        if [ -n "${{ inputs.project }}" ]; then
          echo "name=${{ inputs.project }}" >> "$GITHUB_OUTPUT"
        else
          echo "name=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        fi
    - name: Deploy with Helm
      working-directory: ${{ env.WORK_DIR }}
      shell: bash
      run: |
        helm upgrade --install ${{ steps.vars.outputs.name }} \
          oci://ghcr.io/johnhojohn969/generic-app \
          -f ./projects/${{ steps.vars.outputs.name }}/values.yaml \
          --namespace ${{ steps.vars.outputs.name }} \
          --create-namespace
