name: Build & Push App Images
description: Build and push Docker images for backend and frontend

inputs:
  backend-dir:
    description: "Path to backend Dockerfile (default: ./app)"
    required: false
    default: ./app
  frontend-dir:
    description: "Path to frontend Dockerfile (default: ./frontend)"
    required: false
    default: ./frontend
  tag:
    description: "Image tag to use (default: latest)"
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      shell: bash
      run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Extract repo name for image prefix
      id: repo
      shell: bash
      run: echo "name=$(basename ${{ github.repository }})" >> $GITHUB_OUTPUT

    - name: Build & Push Backend
      shell: bash
      run: |
        docker build -t ghcr.io/${{ github.actor }}/${{ steps.repo.outputs.name }}-backend:${{ inputs.tag }} ${{ inputs.backend-dir }}
        docker push ghcr.io/${{ github.actor }}/${{ steps.repo.outputs.name }}-backend:${{ inputs.tag }}

    - name: Build & Push Frontend
      shell: bash
      run: |
        docker build -t ghcr.io/${{ github.actor }}/${{ steps.repo.outputs.name }}-frontend:${{ inputs.tag }} ${{ inputs.frontend-dir }}
        docker push ghcr.io/${{ github.actor }}/${{ steps.repo.outputs.name }}-frontend:${{ inputs.tag }}
