name: Build & Push App Images
description: Build and push Docker images for backend and frontend

inputs:
  backend-dir:
    description: "Path to backend Dockerfile (default: ./app)"
    required: false
    default: ./app
  frontend-dir:
    description: "Path to frontend Dockerfile (default: ./frontend)"
    required: false
    default: ./frontend
  tag:
    description: "Image tag to use (default: latest)"
    required: false
    default: latest
  registry-token:
    description: "Token used to login to ghcr.io"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      shell: bash
      run: |
        REGISTRY_USER="${{ github.triggering_actor || github.actor }}"
        echo "${{ inputs.registry-token }}" | docker login ghcr.io -u "$REGISTRY_USER" --password-stdin

    - name: Extract repo name for image prefix
      id: repo
      shell: bash
      run: |
        repo_name=$(basename "${{ github.repository }}")
        echo "name=${repo_name,,}" >> "$GITHUB_OUTPUT"

    - name: Build & Push Backend
      working-directory: ${{ env.WORK_DIR }}
      shell: bash
      run: |
        if [ ! -d "${{ inputs.backend-dir }}" ]; then
          echo "Backend directory '${{ inputs.backend-dir }}' does not exist" >&2
          exit 1
        fi
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}-backend:${{ inputs.tag }} ${{ inputs.backend-dir }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}-backend:${{ inputs.tag }}

    - name: Build & Push Frontend
      working-directory: ${{ env.WORK_DIR }}
      shell: bash
      run: |
        if [ ! -d "${{ inputs.frontend-dir }}" ]; then
          echo "Frontend directory '${{ inputs.frontend-dir }}' does not exist" >&2
          exit 1
        fi
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}-frontend:${{ inputs.tag }} ${{ inputs.frontend-dir }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}-frontend:${{ inputs.tag }}
