name: Build & Push App Image
description: Build and push a Docker image for the application

inputs:
  app-dir:
    description: "Path to application Dockerfile (default: ./app)"
    required: false
    default: ./app
  tag:
    description: "Image tag to use (default: latest)"
    required: false
    default: latest
  registry-token:
    description: "Token used to login to ghcr.io"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      shell: bash
      run: |
        REGISTRY_USER="${{ github.triggering_actor || github.actor }}"
        echo "${{ inputs.registry-token }}" | docker login ghcr.io -u "$REGISTRY_USER" --password-stdin

    - name: Extract repo name for image prefix
      id: repo
      shell: bash
      run: |
        repo_name=$(basename "${{ github.repository }}")
        echo "name=${repo_name,,}" >> "$GITHUB_OUTPUT"

    - name: Build & Push Image
      working-directory: ${{ env.WORK_DIR }}
      shell: bash
      run: |
        if [ ! -d "${{ inputs.app-dir }}" ]; then
          echo "App directory '${{ inputs.app-dir }}' does not exist" >&2
          exit 1
        fi
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}:${{ inputs.tag }} ${{ inputs.app-dir }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}:${{ inputs.tag }}
