name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      project:
        description: "Project folder under ./projects containing values.yaml"
        required: true
      suffix:
        description: "Optional suffix appended to the ephemeral folder name"
        required: false
        default: ''
      app-dir:
        description: "Path to application Dockerfile"
        required: false
        default: './app'
      registry-token:
        description: "Token used to login to ghcr.io (defaults to GIT_PAT secret)"
        required: false
        default: ''

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: johnhojohn969/setup-ephemeral-action/.github/actions/build-and-deploy@main
        with:
          project: ${{ inputs.project }}
          suffix: ${{ inputs.suffix }}
          app-dir: ${{ inputs.app-dir }}
          registry-token: ${{ inputs.registry-token || secrets.GIT_PAT }}
