name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      project:
        description: "Project folder under ./projects containing values.yaml"
        required: true
      suffix:
        description: "Optional suffix appended to the ephemeral folder name"
        required: false
        default: ''

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: johnhojohn969/setup-ephemeral-action/.github/actions/build-and-deploy@main
        with:
          project: ${{ inputs.project }}
          suffix: ${{ inputs.suffix }}
