name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      project:
        description: "Project folder under ./projects containing values.yaml"
        required: true
      suffix:
        description: "Optional suffix appended to the ephemeral folder name"
        required: false
        default: ''
      backend-dir:
        description: "Path to backend Dockerfile"
        required: false
        default: './app'
      frontend-dir:
        description: "Path to frontend Dockerfile"
        required: false
        default: './frontend'
      registry-token:
        description: "Token used to login to ghcr.io"
        required: false
        default: ''

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: johnhojohn969/setup-ephemeral-action/.github/actions/build-and-deploy@main
        with:
          project: ${{ inputs.project }}
          suffix: ${{ inputs.suffix }}
          backend-dir: ${{ inputs.backend-dir }}
          frontend-dir: ${{ inputs.frontend-dir }}
          registry-token: ${{ inputs.registry-token }}
