name: Push Generic Chart

on:
  workflow_dispatch:
  push:
    paths:
      - 'charts/generic-app/**'

permissions:
  contents: read
  packages: write

jobs:
  push-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/helm-push
        with:
          chart-path: charts/generic-app
          registry: oci://ghcr.io/johnhojohn969
          registry-token: ${{ secrets.GIT_PAT }}

